from __future__ import annotations

import logging
from typing import List

from ..base.agent_context import AgentContext
from ..base.capability_router import CapabilityRouter
from .execution_plan import ExecutionPlan

logger = logging.getLogger(__name__)


class ExecutionEngine:
    """
    Executes workflow capabilities sequentially.

    Responsibilities
    ----------------
    - Execute an ExecutionPlan
    - Resolve capabilities to agents
    - Execute agents
    - Update shared AgentContext
    - Record execution history

    This class DOES NOT:
        - Choose workflows
        - Plan execution
        - Know business logic
        - Know concrete agent implementations
    """

    def __init__(
        self,
        capability_router: CapabilityRouter,
    ) -> None:

        self.router = capability_router

    # ---------------------------------------------------------
    # Public Execution
    # ---------------------------------------------------------

    async def execute_plan(
        self,
        execution_plan: ExecutionPlan,
        context: AgentContext,
    ) -> AgentContext:
        """
        Executes every workflow step contained in the ExecutionPlan.

        Parameters
        ----------
        execution_plan:
            Execution plan generated by the Planner.

        context:
            Shared AgentContext.

        Returns
        -------
        AgentContext
            Updated context after all agents have executed.
        """

        logger.info(
            "Executing workflow '%s' (%d steps).",
            execution_plan.workflow_name,
            execution_plan.total_steps(),
        )

        execution_plan.status = "RUNNING"

        for node in execution_plan.steps:

            context.current_step = node.capability

            logger.info(
                "Executing capability: %s",
                node.capability,
            )

            agent = self.router.route(node.capability)

            context = await agent.execute(context)

            context.add_execution_step(
                agent_name=agent.name,
                status="SUCCESS",
                details=node.capability,
            )

        execution_plan.status = "COMPLETED"

        logger.info(
            "Workflow '%s' completed successfully.",
            execution_plan.workflow_name,
        )

        return context

    # ---------------------------------------------------------
    # Preview
    # ---------------------------------------------------------

    def preview_execution_plan(
        self,
        execution_plan: ExecutionPlan,
    ) -> List[str]:
        """
        Returns the ordered list of capabilities
        without executing the workflow.

        Useful for UI previews and debugging.
        """

        return execution_plan.capabilities()